sudo: required
dist: trusty
language: python

matrix:
  include:
  - python: "2.7"
    env: OPENCV_VERSION=3.2.0
  - python: "3.4"
    env: OPENCV_VERSION=3.2.0
  - python: "3.5"
    env: OPENCV_VERSION=3.2.0
  - python: "3.6"
    env: OPENCV_VERSION=3.2.0
  - python: "2.7"
    env: OPENCV_VERSION=2.4.13.2
  - python: "3.4"
    env: OPENCV_VERSION=2.4.13.2
  - python: "3.5"
    env: OPENCV_VERSION=2.4.13.2
  - python: "3.6"
    env: OPENCV_VERSION=2.4.13.2
  
env:
  global:
    - OPENCV_SRC_PATH=$HOME/opencv_src
    - OPENCV_INSTALL_PATH=$HOME/opencv_install
  
cache:
  pip: true
  directories:
    - $OPENCV_INSTALL_PATH

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libswscale-dev libgtk2.0-dev
  - sudo apt-get install -y python-tk python3-tk
  - bash travis/build_opencv.sh

install:
  - pip install -r requirements.txt
  - pip install codecov

script: coverage run --source=cvbase setup.py test

after_success: codecov

deploy:
  provider: pypi
  user: kchen
  password:
    secure: VLaJH6buurJJRVVSiya/yy65oBppF7I6Ylt242P84KdhCyVErnG+N8T0/JRr2d8rQas3h/11K9ev3ybDhZ67atkCRcSqVu3JZJaHLVCtdY4PmV9o7YSKIrTUYCqUceCR1y4cifDk6cbHkUO4zLXfte6ZIixIKRQrGCnImBTWUtQQ4w1Snm5UUk2lNMHGD0mbeDg/Q3SmF0LEtydcCcg2nDh/87rCGyoyZQa3C39CVjyGCbBGCFLhShJ3RsFmHUILshrJM1LXFRSxL0ykwPSxcT6WTz7930/OiJ4qmD8okn/waAr6JHI6g/xAAAybyNZo+g8uRWTnhWJ6bg9D0vJ3Td4EoFUJDZb813NFGRpysWu3ynjREsyzHLHHI+fKkxnSDrng7lM3tqEQjGazyeIzQEWLqeNaQRcyTZ4QcCcm8QNTbHLKNApIMMOflgEVlgwndrA4CNgmUUnl3oDp+yRZ44Dc2zXwbSih1/wkX+OZx3Y3C6zuBmQ3LippmWk+bjlqAvAzK96YRHxaDsImZqpwjOZkijiUOsjgEzs41hlQ9f6ONB5pPTlz8mpfmYe2OLhMIlU6NutnWjV1xeNWGesjmd6Y9RjnEquitAFwTqj8edE681WbFmDXv2foX8Apbn3GAgcs4SHiK/vApOB/T/HBIYw1ud5YUtkz9MlZIlDvkgg=
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true